### ISSUE TITLE
Available from conda-forge

### ISSUE THREAD

**Issue by hoechenberger** [hbldh/lspopt#7]
Hello, thanks to recent release, I was able to package LSPOpt for conda-forge:
https://github.com/conda-forge/lspopt-feedstock

Not sure if you want to add this source to the installation instructions too

Also please let me know if you'd like to be a co-maintainer of the conda-forge feedstock repository (which basically boils down to having to adjust the list of dependencies should they ever change upstream)

**Comment by hbldh** [comment]
LSPOpt is not a package in active development. It is done and "non-maintained". I only put it up on PyPI because three people asked me to (See #1). You are welcome to provide it through conda-forge, but as I am not a user of the conda ecosystem I do not think I will be of any use. It is nice to see that people have a use for LSPOpt though, and that I want to encourage as long as it does not include much more than editing a MANIFEST.in and doing a new release.

**Comment by hoechenberger** [comment]
Alright, thank you for the information!
